version: "1"
rules: # Array of rules
  - base: master # Required. Target branch
    upstream: TeamNewPipe:master # Required. Must be in the same fork network.
    mergeMethod: hardreset # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
    mergeUnstable: true # Optional, merge pull request even when the mergeable_state is not clean. Default: false
  - base: dev # Required. Target branch
    upstream: TeamNewPipe:dev # Required. Must be in the same fork network.
    mergeMethod: hardreset # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
    mergeUnstable: true # Optional, merge pull request even when the mergeable_state is not clean. Default: false
  - base: refactor # Required. Target branch
    upstream: TeamNewPipe:refactor # Required. Must be in the same fork network.
    mergeMethod: hardreset # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
    mergeUnstable: true # Optional, merge pull request even when the mergeable_state is not clean. Default: false  
